### ISSUE TITLE
Tillåt elasticsearch alias till index

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#182]
lägg till hantering av `InvalidIndexNameException` när `initalization` av elastic körs i `rinfo-service`
m.h.a alias blir det lättare att hotswappa index

**Comment by jeldeklint** [comment]
@cheijken @karejonssondov  testar ni det här?

**Comment by cheijken** [comment]
Testat på valle.
Före.
*********************************************
15-04-14 15:36:36  WARN org.restlet.VirtualHost:230 - Unable to start the Restlet [ajp-bio-8009-exec-1]
org.elasticsearch.indices.InvalidIndexNameException: [rinfo_3] Invalid index name [rinfo_3], already exists as alias
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:197) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:559) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:87) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:243) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:352) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:184) ~[elasticsearch-1.4.4.jar:na]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:154) ~[elasticsearch-1.4.4.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
15-04-14 15:39:14 ERROR org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/rinfo-service]:185 - RestServlet: Error during the stopping of the Restlet component [ContainerBackgroundProcessor[StandardEngine[Catalina]]]
*********************************************************'
Efter (med ny kod installerad)
****************************************************************
15-04-14 15:41:09  INFO se.lagrummet.rinfo.service.ElasticData:-1 - ElasticSearch index 'rinfo' already exists. [ajp-bio-8009-exec-2]
15-04-14 15:41:09  INFO se.lagrummet.rinfo.service.ElasticData:-1 - ElasticSearch index 'rinfo' already exists. [ajp-bio-8009-exec-2]
*****************************************************************
Verifierat att det fungerar som vanligt.
Test ok. Kör in i develop.
